name: a11y Tests

on:
  push:
    branches: [main]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [main]
  schedule:
    - cron: '0 4 * * 3'
      
jobs:
  accessibility_job:
    runs-on: ubuntu-latest
    name: Runs accessibility tests
    steps:
      - name: Run a11y tests
        uses: omboo/a11y-action@v0.3-beta.1
        with:
          urls: "https://stritti.github.io/covid-ampel-widget/lkr/211"
          fail-on-error: true
          wait-on: "https://stritti.github.io/covid-ampel-widget/lkr/211"
          wait-on-timeout: 60
