name: a11y Tests

on:
  push:
    branches: [main]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [main]
  schedule:
    - cron: '0 4 * * 3'
      
jobs:
  accessibility_job:
    runs-on: ubuntu-latest
    name: Runs accessibility tests
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install NPM dependencies
        uses: bahmutov/npm-install@v1
      - name: Run build
        run: npm run build
      - name: Run a11y tests
        uses: omboo/a11y-action@v0.3
        with:
          urls: "http://localhost:3000"
          fail-on-error: true
          start-command: "npm start"
          wait-on: "http://localhost:3000"
          wait-on-timeout: 60
